image:
  repository: ghcr.io/platform-engineer-lab/spring-service
  tag: 7a493a7
  pullPolicy: IfNotPresent

service:
  port: 8080

replicaCount: 1

hostname: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

rollout:
  canary:
    steps:
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 100
