apiVersion: v1
kind: Service
metadata:
  name: spring-service-stable
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-service
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service-canary
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: spring-service
spec:
  hostnames:
    - spring.platformlab.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: podinfo
      namespace: podinfo
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: spring-service-stable
          port: 8080
          weight: 100
        - group: ""
          kind: Service
          name: spring-service-canary
          port: 8080
          weight: 0
      matches:
        - path:
            type: PathPrefix
            value: /
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: spring-service
  name: spring-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-service
  strategy:
    canary:
      canaryService: spring-service-canary
      stableService: spring-service-stable
      steps:
        - setWeight: 25
        - pause:
            duration: 60s
        - setWeight: 50
        - pause:
            duration: 60s
        - setWeight: 75
        - pause:
            duration: 60s
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
        - image: ghcr.io/platform-engineer-lab/spring-service:127a2c4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          name: spring-service
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
