replicaCount: 1
hostname: spring-dev.platformlab.com
cluster: dev
rollout:
  canary:
    analysis:
      enabled: true
    steps:
      - setWeight: 50
      - pause:
          duration: 40s
      - setWeight: 100
